### ISSUE TITLE
[Android Bootcamp] Group Project Milestone 2 - Ready for Review

### ISSUE THREAD

**Issue by teekirol** [codepath-movie-app/trailer-trash#14]
![trailertrash](https://cloud.githubusercontent.com/assets/829596/6609766/3837b500-c813-11e4-8bc5-10402fc9ef22.gif)

**Comment by rohenp** [comment]
Group gif (user relational data and other fragment dependent for full population.

![groupview](https://cloud.githubusercontent.com/assets/1127775/6610100/c059c3c0-c817-11e4-9183-59cb70990ce3.gif)

**Comment by priyam** [comment]
Planning flow (should follow when user selecs Yay from the first gif):
![planningactivitydemo1](https://cloud.githubusercontent.com/assets/769269/6601623/e64446da-c7d3-11e4-8504-4eedfe8c6f6b.gif)

**Comment by codepathreview** [comment]
:+1: Excellent work creating neat wire-frames and distributing stories/tasks in sprint 1. Great to see the basic screens and flow coming along well. Few notes to mention:

* Well created detailed stories/tasks on the project wiki.
* Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
* Good job by everyone to [contribute](https://github.com/codepath-movie-app/trailer-trash/graphs/contributors) to the project 
* Nice work creating and distributing tasks to create database schema and models.
* Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on.  It is those little extra things you do that make everything feel more polished and desirable to use.
