### ISSUE TITLE
Sprint 2 submission is ready

### ISSUE THREAD

**Issue by priyam** [codepath-movie-app/trailer-trash#38]
Sprint 2 submission with core functionality of the app is ready for review.

### Login and Sign up
- Required: Login with Facebook via OAuth
- Required: Settings page to select movie sort order and genres. Saved on server.

### Movies list view and details
- Required: Display a list of upcoming movies (unreleased to theatres), only in the genres that the user selected in the previous screen. Tapping an item will launch a new screen displaying the movie details.
- Required: User can play the movie trailer from the list view or detailed view of the movie
- Required: User can add a movie to their watch list by pressing the Save button

### Settings
- Required: User can tap on a settings icon in the Action Bar and go to the Settings page
- Required: User can log out from the settings page
- Optional: User can change their genre preferences from the settings page
- Optional: User can change the movie list sort order from the settings page (Hot, New, Closest Release Date)

### Social + Date, Time & Theatre selection
- Required : User can view a list of their Facebook friends
- Required: User can invite their Facebook friends who are using this app to watch a movie.
- Required: User can select a time and theatre where a movie is playing
- Optional : User can view a list of their Facebook friends who want to watch a given movie

### Movie Groups
- Required: A user who is invited to a movie can vote Going or not going
- Required: The user who initiated a viewing can close the vote at any time. Users who voted in will receive a notification.
- Required: User can view a list of movies that they are interested in watching. Movies in the list will be grouped as one of three:
 - Planned - a date, time and location have been selected
 - Planning - voting is in progress
 - No Plan - voting has not begun

 Here is the gif walkthrough:
![trailertrashweek2](https://cloud.githubusercontent.com/assets/769269/6702853/5fb6efa2-ccef-11e4-9fc4-e6565b344311.gif)

**Comment by codepathreview** [comment]
:+1: Excellent work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

* Good job on achieving your sprint 2 milestone. Glad to see you created and assigned tasks to everyone so that everyone has equal opportunity to learn.
* Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
* Try to challenge yourself on the UI/visual side of things in the coming days. Not necessarily flashy things, but it's the small details that take a lot of work.
* Keep working on integrating the core flows/nice to have features and make sure all pieces fit together perfectly.
* Consult with your mentors to get their feedback as often as you can. Remember they are here to help!
* While working on polishing your app for next sprint, remember that your app follows the [android design guidelines] (http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns] (http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
